# Generated by Django 2.1.7 on 2022-07-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='select',
            field=models.CharField(choices=[('tweet', 'tweet'), ('video', 'tweet'), ('image', 'image')], default='tweet', max_length=100),
        ),
    ]
