# Generated by Django 2.1.7 on 2022-07-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='select',
            field=models.CharField(choices=[('tweet', 'tweet'), ('video', 'video'), ('image', 'image')], default='tweet', max_length=100),
        ),
    ]
