# Generated by Django 4.0.6 on 2022-07-24 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20220712_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='select',
        ),
        migrations.AddField(
            model_name='post',
            name='From',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contact_type',
            field=models.CharField(choices=[('Contact Name', 'Contact Name'), ('Company', 'Company')], default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('OTHERS', 'OTHERS')], default='n', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='email_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='form_choice',
            field=models.CharField(blank=2, max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('DRAMA', 'DRAMA'), ('THRLLER', 'THRILLER'), ('ROMANCE', 'ROMANCE'), ('SCI-FI', 'SCI-FI')], default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='price_per_day',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='rent_option',
            field=models.CharField(choices=[('Location', 'Location'), ('Equipment', 'Equipment')], default='n', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='show',
            field=models.CharField(choices=[('Short Film', 'Short Film'), ('Feature Film', 'Feature Film'), ('Documentory', 'Documentory'), ('Series', 'Series')], default='n', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='show_language',
            field=models.CharField(choices=[('TAMIL', 'TAMIL'), ('TELEGU', 'TELEGU'), ('MALAYALAM', 'MALAYALAM'), ('ENGLISH', 'ENGLISH')], default='n', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='talent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
