# Generated by Django 4.0.6 on 2022-07-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='talent',
            field=models.CharField(choices=[('Script Writer', 'Pre-Prod-Script Writer'), ('Storyboard Artist', 'Pre-Prod-Storyboard Artist'), ('Executive Producer', 'Pre-Prod-Executive Producer'), ('Location', 'Prod-Location'), ('Camera Rents', 'Prod-Camera Rents'), ('Equiepments', 'Prod-Equiepments'), ('Lightman', 'Prod-Lightman'), ('Makeup', 'Prod-Makeup'), ('Stunt', 'Prod-Stunt'), ('Editor', 'Post-Prod-Editor'), ('Dubbing Engineer', 'Post-Prod-Dubbing Engineer'), ('Sound Engineer', 'Post-Prod-Sound Engineer'), ('Music Director', 'Post-Prod-Music Director'), ('Sound Mixing', 'Post-Prod-Sound Mixing'), ('Colorist', 'Post-Prod-Colorist')], max_length=50),
        ),
    ]
