# Generated by Django 4.0.6 on 2022-07-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_talent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='talent',
            field=models.CharField(choices=[('Actor', 'Actor'), ('Actress', 'Actress'), ('Director', 'Director'), ('Associate Director', 'Associate Director'), ('Assistant Director', 'Assistant Director'), ('Child Artist', 'Child Artist'), ('Dubbing Artist', 'Dubbing Artist'), ('Script Writer', 'Pre-Prod-Script Writer'), ('Storyboard Artist', 'Pre-Prod-Storyboard Artist'), ('Executive Producer', 'Pre-Prod-Executive Producer'), ('Location', 'Prod-Location manager'), ('Production manager', 'Production Manager'), ('Camera Rents', 'Prod-Camera Rents'), ('Art Director', 'Art Director'), ('Lightman', 'Prod-Lightman'), ('Makeup', 'Prod-Makeup'), ('Stunt', 'Prod-Stunt'), ('Editor', 'Post-Prod-Editor'), ('Dubbing Engineer', 'Post-Prod-Dubbing Engineer'), ('Sound Engineer', 'Post-Prod-Sound Engineer'), ('Music Director', 'Post-Prod-Music Director'), ('Sound Mixing', 'Post-Prod-Sound Mixing'), ('Colorist', 'Post-Prod-Colorist'), ('Pubicity Design', 'Pubicity Design')], max_length=50),
        ),
    ]
