# Generated by Django 4.0.6 on 2022-07-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_talent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='talent',
            field=models.CharField(choices=[('Actor', 'Actor'), ('Actress', 'Actress'), ('Director', 'Director'), ('Associate Director', 'Associate Director'), ('Assistant Director', 'Assistant Director'), ('Child Artist', 'Child Artist'), ('Dubbing Artist', 'Dubbing Artist'), ('Script Writer', 'Script Writer'), ('Storyboard Artist', 'Storyboard Artist'), ('Executive Producer', 'Executive Producer'), ('Location', 'Location manager'), ('Production manager', 'Production Manager'), ('Art Director', 'Art Director'), ('Lightman', 'Lightman'), ('Makeup', 'Makeup'), ('Stunt', 'Stunt'), ('Editor', 'Editor'), ('Dubbing Engineer', 'Dubbing Engineer'), ('Sound Engineer', 'Sound Engineer'), ('Music Director', 'Music Director'), ('Sound Mixing', 'Sound Mixing'), ('Colorist', 'Colorist'), ('Pubicity Design', 'Pubicity Design'), ('Others', 'Others')], max_length=50),
        ),
    ]
